---
# OS RELEASE: RHEL 7 and RHEL 8
# SAP Note: 2526952 - Red Hat Enterprise Linux for SAP Solutions
# prerequisite: package tuned-profiles-sap is installed (see vars/RedHat.yml)

# Configure tuned to use profile "sap-netweaver"

- name: Enable and start tuned
  service:
    name=tuned
    state=started
    enabled=yes

- name: Show currently active tuned profile
  shell: /usr/sbin/tuned-adm active | awk '/:/{print $NF}'
  check_mode: no
  register: __sap_netweaver_preconfigure_register_current_tuned_profile
  changed_when: false

- debug:
    var: __sap_netweaver_preconfigure_register_current_tuned_profile.stdout_lines, __sap_netweaver_preconfigure_register_current_tuned_profile.stderr_lines

- set_fact:
    __sap_netweaver_preconfigure_register_active_tuned_profile: "{{ __sap_netweaver_preconfigure_register_current_tuned_profile.stdout }}"

- name: Switch to tuned profile sap-netweaver if not currently active
  block:
    - name: Switch to tuned profile sap-netweaver
      command: /usr/sbin/tuned-adm profile sap-netweaver

    - name: Show new active tuned profile
      shell: /usr/sbin/tuned-adm active | awk '{print $NF}'
      check_mode: no
      register: __sap_netweaver_preconfigure_register_new_tuned_profile
      changed_when: false

    - debug:
        var: __sap_netweaver_preconfigure_register_new_tuned_profile.stdout_lines, __sap_netweaver_preconfigure_register_new_tuned_profile.stderr_lines

    - set_fact:
        __sap_netweaver_preconfigure_register_active_tuned_profile: "{{ __sap_netweaver_preconfigure_register_new_tuned_profile.stdout }}"
  when:
    - __sap_netweaver_preconfigure_register_current_tuned_profile.stdout != 'sap-netweaver'

...
